db:
  image: postgres
web:
  dockerfile: Dockerfile
  build: .
  links:
    - db
  environment:
    - NODE_ENV=production
    - PORT=9000
    - DB_HOST=db
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - DB_DATABASE=solutions
  ports:
    - '80:80'
    - '443:443'
