db:
  image: postgres
web:
  dockerfile: Dockerfile
  build: .
  links:
    - db
  environment:
    - NODE_ENV=production
    - PORT=9000
    - NODE_ENV=development
    - DB_HOST=db
    - DB_USER=postgres
    - DB_PASSWORD=postgres
  ports:
    - '80'
    - '443'
